apiVersion: v1
kind: Pod
metadata:
  name: tacos-cloud
  namespace: default
  labels:
    name: tacos-cloud
spec:
  containers:
    - image: panda2021/tacos-cloud:latest
      name: tacos-cloud
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP