apiVersion: v1
kind: Pod
metadata:
  name: spring-gumball
  namespace: default
  labels:
    name: spring-gumball
spec:
  containers:
    - image: panda2021/spring-gumball:v1
      name: spring-gumball
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
